'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),crypto=require('node:crypto');
const C=require('../cs50/obsidian/src/core.cjs'),{Cloud}=require('../cs50/obsidian/src/transport.cjs'),{Engine,initial,validateState}=require('../cs50/obsidian/src/engine.cjs');
const account='11111111-1111-4111-8111-111111111111';
const yaml={parseYaml:s=>Object.fromEntries(s.split('\n').filter(Boolean).map(l=>{const i=l.indexOf(':');return[l.slice(0,i),JSON.parse(l.slice(i+1))];})),stringifyYaml:o=>Object.entries(o).map(([k,v])=>k+': '+JSON.stringify(v)).join('\n')+'\n'};
function note(title='Functions',text='Original'){return C.newEvent({release_id:'notebook-'+crypto.randomUUID(),title,text,topics:['p-functions'],aliases:[],archived:false},{},[]);}
function fixture(events=[]){const files=new Map(),cloud={session:{user:{id:account}},events:C.clone(events),allowed:true,async requireAccess(){if(!this.allowed)throw new Error('denied');return{id:account};},async pull(){await this.requireAccess();return C.clone(this.events);},async push(e){await this.requireAccess();this.events=C.mergeEvents(this.events,[e]);}};let state=initial();state.account=account;let saved=initial();const conflict=new Map();const port={...yaml,async list(){return [...files.keys()].filter(C.managedPath);},async read(p){if(!files.has(p))throw Error('missing');return files.get(p);},async exists(p){return files.has(p);},async create(p,t){assert(!files.has(p));files.set(p,t);return true;},async replace(p,b,n){if(files.get(p)!==b)return false;files.set(p,n);return true;},async conflict(id,e){conflict.set(e.id,e);},async confirmMerge(){return true;}};const save=async x=>saved=C.clone(x);const engine=new Engine(port,cloud,state,save);return{engine,state,port,cloud,files,conflict,save,get saved(){return saved;}};}
function edit(f,id,text,title){const en=f.state.entries[id];const doc=C.split(f.files.get(en.path),yaml.parseYaml);if(title)doc.meta.tomato08_title=title;f.files.set(en.path,'---\n'+yaml.stringifyYaml(doc.meta)+'---\n'+text);}

test('matches website note validation and ledger envelope',()=>{const e=note();assert(C.validEvent(e));const original=require('../cs50/path/notes-core.js');assert(original.valid(e));require('../cs50/studio/core.js').validateEvent(e);});
test('canonical identity permits PostgreSQL timestamp serialization',()=>{const e=note();const d={...C.clone(e),client_at:e.client_at.replace('Z','+00:00')};assert.equal(C.mergeEvents([e],[d]).length,1);});
test('immutable collisions and malformed note events stop',()=>{const e=note(),other=C.clone(e);other.payload.text='changed';assert.throws(()=>C.mergeEvents([e],[other]),/collision/);assert.throws(()=>C.mergeEvents([], [{...e,id:'bad'}]));});
test('foreign-note or missing ancestry stops rather than overwriting',()=>{const a=note(),b=note('Other');const e=C.newEvent(a.payload,{},[b.id]);assert.throws(()=>C.groups([a,b,e]),/cross-note/);assert.throws(()=>C.groups([e]),/Incomplete/);});
test('path traversal and unsafe filenames are not allowed',()=>{assert(!C.managedPath('Tomato08/Notes/../../x.md'));assert(!C.managedPath('Other/note.md'));assert(!C.managedPath('Tomato08/Notes/.secret.md'));assert(!C.managedPath('Tomato08/Notes/C:\\x.md'));assert(!C.basename('CON',note().payload.release_id).startsWith('CON'));});
test('two heads are retained without last-write-wins',()=>{const a=note(),b=C.newEvent(a.payload,{text:'B'},[a.id]),c=C.newEvent(a.payload,{text:'C'},[a.id]);assert.equal(C.groups([a,b,c]).get(a.payload.release_id).length,2);});
test('round-trip metadata and links work; code and embeds stay literal',()=>{const a=note('Functions'),b=note('Loops');const all=C.groups([a,b]),idx=C.linkIndex(all,{});const text='See [[Loops]] and `[[Loops]]`.\n```python\n[[Loops]]\n```\n![[image.png]]';const v=C.toVault(text,idx,{});assert(v.includes(C.defaultPath(b.payload).replace('.md','')));assert(v.includes('`[[Loops]]`'));assert(v.includes('![[image.png]]'));const back=C.toWeb(v,idx);assert(back.includes('[['+b.payload.release_id+'|Loops]]'));});
test('ambiguous titles and heading links are not silently redirected',()=>{const a=note('Duplicate'),b=note('Duplicate');const idx=C.linkIndex(C.groups([a,b]),{});assert.equal(C.toVault('[[Duplicate]] [[Other#Heading]]',idx,{}),'[[Duplicate]] [[Other#Heading]]');});
test('downloads website note as real managed Markdown',async()=>{const a=note(),f=fixture([a]);const r=await f.engine.sync();assert.equal(r.pulled,1);assert.equal(f.files.size,1);const en=f.state.entries[a.payload.release_id];assert(f.files.get(en.path).endsWith('Original'));assert.equal(f.cloud.events.length,1);});
test('unchanged sync is idempotent including converted wikilinks',async()=>{const a=note('Functions','See [[Loops]]'),b=note('Loops'),f=fixture([a,b]);await f.engine.sync();await f.engine.sync();assert.equal(f.cloud.events.length,2);});
test('Obsidian edit and title rename reach website preserving aliases',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();edit(f,id,'Local edit','New name');await f.engine.sync();const hs=C.groups(f.cloud.events).get(id);assert.equal(hs.length,1);assert.equal(hs[0].payload.text,'Local edit');assert(hs[0].payload.aliases.includes('Functions'));});
test('remote edit pulls without touching unrelated properties',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();const en=f.state.entries[id];f.files.set(en.path,f.files.get(en.path).replace('---\n','---\ntags: ["local"]\n'));await f.engine.sync();f.cloud.events.push(C.newEvent(a.payload,{text:'Web edit'},[a.id]));await f.engine.sync();const doc=C.split(f.files.get(en.path),yaml.parseYaml);assert.equal(doc.body,'Web edit');assert.deepEqual(doc.meta.tags,['local']);});
test('simultaneous remote and local edits retain original and both branches',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();edit(f,id,'Local edit');f.cloud.events.push(C.newEvent(a.payload,{text:'Web edit'},[a.id]));const r=await f.engine.sync();assert.equal(r.conflicts,1);assert(f.files.get(f.state.entries[id].path).endsWith('Local edit'));assert.equal(f.conflict.size,2);assert.equal(C.groups(f.cloud.events).get(id).length,2);await f.engine.sync();assert.equal(f.cloud.events.length,3);});
test('explicit merge joins all parents and website sees a single head',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();edit(f,id,'Local');f.cloud.events.push(C.newEvent(a.payload,{text:'Web'},[a.id]));await f.engine.sync();edit(f,id,'Merged both');assert(await f.engine.resolve(id));await f.engine.sync();const hs=C.groups(f.cloud.events).get(id);assert.equal(hs.length,1);assert.equal(hs[0].payload.text,'Merged both');assert.equal(hs[0].payload.parents.length,2);});
test('concurrent edit during asynchronous pull is not overwritten',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();f.cloud.events.push(C.newEvent(a.payload,{text:'Web'},[a.id]));const old=f.port.replace;f.port.replace=async(p,b,n)=>{f.files.set(p,f.files.get(p)+' typing');return old(p,b,n);};const r=await f.engine.sync();assert.equal(r.deferred,1);assert(f.files.get(f.state.entries[id].path).endsWith('Original typing'));});
test('local file deletion never deletes cloud records or recreates file silently',async()=>{const a=note(),f=fixture([a]);await f.engine.sync();f.files.clear();const r=await f.engine.sync();assert.equal(r.missing,1);assert.equal(f.files.size,0);assert.equal(f.cloud.events.length,1);});
test('archive preserves local content and only updates its property',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();f.cloud.events.push(C.newEvent(a.payload,{archived:true},[a.id]));await f.engine.sync();const d=C.split(f.files.get(f.state.entries[id].path),yaml.parseYaml);assert.equal(d.meta.tomato08_archived,true);assert.equal(d.body,'Original');});
test('durable outbox retries unknown network outcome with the same event ID',async()=>{const a=note(),f=fixture([a]),id=a.payload.release_id;await f.engine.sync();edit(f,id,'Retry me');let first=true;const push=f.cloud.push.bind(f.cloud);f.cloud.push=async e=>{await push(e);if(first){first=false;throw new Error('Lost response');}};await assert.rejects(f.engine.sync(),/Lost response/);assert.equal(f.saved.pending.length,1);const pending=f.saved.pending[0];await f.engine.sync();assert.equal(f.state.pending.length,0);assert.equal(f.cloud.events.filter(e=>e.id===pending).length,1);});
test('new locally authored managed note publishes without touching originals',async()=>{const f=fixture();f.files.set('Other/private.md','private');const p=await f.engine.add('Fresh','local body');await f.engine.sync();assert.equal(f.cloud.events.length,1);assert.equal(f.files.get('Other/private.md'),'private');assert(f.files.has(p));});
test('unmarked files in managed folder are never uploaded',async()=>{const f=fixture();f.files.set('Tomato08/Notes/private.md','Do not upload');await f.engine.sync();assert.equal(f.cloud.events.length,0);});
test('duplicate managed note IDs stop and preserve both files',async()=>{const a=note(),f=fixture([a]);await f.engine.sync();f.files.set('Tomato08/Notes/copy.md',[...f.files.values()][0]);await assert.rejects(f.engine.sync(),/Duplicate/);assert.equal(f.files.size,2);});
test('wrong-account managed note never leaks into this account',async()=>{const a=note(),f=fixture([a]);await f.engine.sync();const en=f.state.entries[a.payload.release_id];f.files.set(en.path,f.files.get(en.path).replace(account,'22222222-2222-4222-8222-222222222222'));await assert.rejects(f.engine.sync(),/account/);assert.equal(f.cloud.events.length,1);});
test('lost plugin state safely adopts unchanged metadata; preserves an edited offline copy',async()=>{const a=note(),f=fixture([a]);await f.engine.sync();const id=a.payload.release_id;edit(f,id,'offline recovery');const recovered=initial();recovered.account=account;const engine=new Engine(f.port,f.cloud,recovered,async()=>{});await engine.sync();assert.equal(C.groups(f.cloud.events).get(id)[0].payload.text,'offline recovery');});
test('invalid stored state fails without being reset',()=>{assert.throws(()=>validateState({schema:9}),/Unsupported/);assert.equal(initial().account,null);});
test('access denial makes no file or cloud modifications',async()=>{const a=note(),f=fixture([a]);f.cloud.allowed=false;await assert.rejects(f.engine.sync(),/denied/);assert.equal(f.files.size,0);assert.equal(f.cloud.events.length,1);});
test('two parallel sync invocations are not allowed',async()=>{const f=fixture();f.engine.busy=true;await assert.rejects(f.engine.sync(),/already/);});
test('transport never stores a password or accepts another account token',()=>{const c=new Cloud(async()=>{},account);assert.throws(()=>c.setSession({access_token:'a',refresh_token:'r',user:{id:'22222222-2222-4222-8222-222222222222'}}),/another account/);assert.equal(c.session,null);assert(!('password'in c));});
test('HTTP transport authenticates and fails closed when access response is malformed',async()=>{const calls=[],c=new Cloud(async opts=>{calls.push(opts);return {status:200,json:opts.url.endsWith('/user')?{id:account}:{} };},account);c.setSession({access_token:'token',refresh_token:'refresh',user:{id:account},expires_at:Date.now()/1000+9999});await assert.rejects(c.requireAccess(),/Invalid access/);assert(calls.every(x=>x.url.startsWith('https://semtnzdzpluhnkzxkquk.supabase.co/')));assert(calls.every(x=>x.headers.Authorization==='Bearer token'));});
test('MFA transport creates then verifies challenge and checks approved access',async()=>{const fid=crypto.randomUUID(),cid=crypto.randomUUID(),calls=[];const c=new Cloud(async o=>{calls.push(o);let json;if(o.url.endsWith('/challenge'))json={id:cid};else if(o.url.endsWith('/verify'))json={access_token:'aal2-token',refresh_token:'r2',expires_in:3600};else if(o.url.endsWith('/user'))json={id:account};else json={allowed:true,user_id:account};return {status:200,json};},account);c.setSession({access_token:'a',refresh_token:'r',user:{id:account},expires_in:3600});await c.verify(fid,'123456');assert(calls[0].url.includes(fid+'/challenge'));assert.equal(JSON.parse(calls[1].body).challenge_id,cid);assert.equal(c.session.access_token,'aal2-token');});
test('unload or session change invalidates pending authentication responses',async()=>{let done;const c=new Cloud(()=>new Promise(resolve=>done=resolve));const call=c.login('stud01','secret');c.clear();done({status:200,json:{access_token:'a',refresh_token:'r',user:{id:account}}});await assert.rejects(call,/Session changed/);assert.equal(c.session,null);});
