'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const core=require('../cs50/drills/core.js');const shared=require('../cs50/studio/core.js');
const index=JSON.parse(fs.readFileSync(path.join(__dirname,'../cs50/drills/index.json')));
const packs=index.topics.map(t=>JSON.parse(fs.readFileSync(path.join(__dirname,'../cs50',t.file))));const tasks=packs.flatMap(p=>p.tasks);
const event=(task,passed=true,extra={})=>({id:crypto.randomUUID(),client_at:'2026-09-20T12:00:00Z',payload:{schema:2,type:'attempt',release_id:task.id,release_version:task.version,assistance:'none',hints:0,provenance:'local-unverified',passed,...extra}});
async function report(t){const code='# Test-only source snapshot; UI validation does not execute code.\n';return {schema:1,kind:'tomato08-python-drill-report',id:crypto.randomUUID(),task_id:t.id,task_version:t.version,topic:t.topic,runner_version:'1.0.0',mode:t.mode,created_at:'2026-09-20T12:00:00Z',trust:'local-unverified',source_files:{'src/solution.py':code},source_sha256:await shared.sourceHash({'src/solution.py':code}),tests_sha256:t.tests_sha256,results:t.cases.map(c=>({id:c.id,passed:true,skipped:false,detail:'UI fixture only'})),passed:true};}
test('12 complete packs, 180 drills, 36 fresh checks, 665 behavior cases',()=>{assert.equal(core.validateCatalog(index,packs),true);assert.equal(tasks.length,216);assert.equal(tasks.filter(t=>t.mode==='practice').length,180);assert.equal(tasks.filter(t=>t.mode==='check').length,36);assert.equal(tasks.reduce((n,t)=>n+t.cases.length,0),665);assert.equal(new Set(tasks.map(t=>t.id)).size,216);});
test('prerequisites point backwards and application handoffs exist',()=>{const seen=new Set();const studio=JSON.parse(fs.readFileSync(path.join(__dirname,'../cs50/studio/catalog.json')));for(const p of packs){for(const id of p.prerequisites)assert.ok(seen.has(id),`${p.id} needs ${id}`);assert.ok(studio.releases.some(r=>r.id===p.project));seen.add(p.id);}});
test('test fingerprints match the complete case contracts',async()=>{for(const t of tasks)assert.equal(await core.hash(core.canonical(t.cases)),t.tests_sha256,t.id);});
test('knowledge checks have different IDs and no built-in hints',()=>{for(const p of packs){assert.equal(p.tasks.filter(t=>t.mode==='check').length,3);for(const t of p.tasks.filter(t=>t.mode==='check'))assert.deepEqual(t.hints,[]);for(const t of p.tasks.filter(t=>t.mode==='practice'))assert.equal(t.hints.length,3);}});
test('mixed queue samples without duplicates and never includes fresh checks',()=>{const q=core.queue(tasks,[],'mixed',50,()=>.25);assert.equal(q.length,50);assert.equal(new Set(q).size,50);assert.ok(q.every(id=>tasks.find(t=>t.id===id).mode==='practice'));});
test('failed and untried pools honor attempt history, not a previous best',()=>{const t=tasks[0],a=event(t,true),b={...event(t,false),client_at:'2026-09-22T12:00:00Z'};assert.deepEqual(core.queue(tasks,[a,b],'failed',10),[t.id]);assert.ok(!core.queue([t],[a,b],'untried',10).length);assert.equal(core.facts([a,b],t).passed,true);assert.equal(core.facts([a,b],t).latest.payload.passed,false);});
test('review pool uses the last pass and a 48-hour practice rule',()=>{const t=tasks[0],e=event(t);assert.equal(core.queue([t],[e],'review',10,Math.random,Date.parse('2026-09-21T12:00:00Z')).length,0);assert.deepEqual(core.queue([t],[e],'review',10,Math.random,Date.parse('2026-09-23T12:00:00Z')),[t.id]);});
test('assisted knowledge check never counts as independently reported',()=>{const p=packs[0],t=p.tasks[15];const s=core.summary([event(t,true,{assistance:'hint',hints:1})],p);assert.equal(s.checks,1);assert.equal(s.independentChecks,0);assert.equal(s.practice,0);});
test('learning steps are deduplicated and cannot manufacture implementation evidence',()=>{const p=packs[0];const es=[1,1,3,99].map(step=>({payload:{type:'trace',kind:'learn-step',release_id:'py-topic-'+p.id,step,version:'1.0.0'}}));assert.equal(core.summary(es,p).learned,2);assert.equal(core.summary(es,p).practice,0);});
test('valid local report passes identity and integrity checks only',async()=>{const t=tasks[0],r=await report(t);assert.equal((await core.validateReport(r,t)).passed,true);assert.equal(r.trust,'local-unverified');});
test('wrong task, mode, version and trusted-grader claims are rejected',async()=>{const t=tasks[0];for(const patch of [{task_id:'py-values-02'},{mode:'check'},{task_version:'2.0.0'},{trust:'verified'},{runner_version:'9'}]){const r=await report(t);await assert.rejects(core.validateReport({...r,...patch},t));}});
test('source tampering, unsafe paths and changed test sets are rejected',async()=>{const t=tasks[0],a=await report(t);a.source_files['src/solution.py']+='modified';await assert.rejects(core.validateReport(a,t));const b=await report(t);b.source_files['../secret.py']='x';await assert.rejects(core.validateReport(b,t));const c=await report(t);c.tests_sha256='0'.repeat(64);await assert.rejects(core.validateReport(c,t));});
test('missing, duplicate, skipped or inconsistent results are rejected',async()=>{const t=tasks[0];let r=await report(t);r.results.pop();await assert.rejects(core.validateReport(r,t));r=await report(t);r.results[1]={...r.results[0]};await assert.rejects(core.validateReport(r,t));r=await report(t);r.results[0].skipped=true;await assert.rejects(core.validateReport(r,t));r=await report(t);r.results[0].passed=false;await assert.rejects(core.validateReport(r,t));r.passed=false;assert.equal((await core.validateReport(r,t)).passed,false);});
test('drill report envelopes remain compatible with existing append-only ledger',async()=>{const t=tasks[0],r=await report(t),e=event(t,true,{report:r});assert.equal(shared.validateEvent(e),e);const d={id:crypto.randomUUID(),client_at:e.client_at,payload:{schema:2,type:'draft',release_id:t.id,parents:[],text:'pass',notes:'fixture',repo:'',assistance:'docs'}};assert.equal(shared.validateEvent(d),d);});
test('course links preserve old paths and avoid ambiguous double entry on Learning page',()=>{const html=fs.readFileSync(path.join(__dirname,'../tester.html'),'utf8');assert.match(html,/href="\.\/cs50\/path\.html"/);assert.ok(!html.includes('href="./cs50/projects.html"'));const corePage=fs.readFileSync(path.join(__dirname,'../cs50/index.html'),'utf8');assert.match(corePage,/data-view="journey"/);assert.match(corePage,/practice.html/);});
test('practice page preserves account gate and does not load an execution runtime',()=>{const html=fs.readFileSync(path.join(__dirname,'../cs50/practice.html'),'utf8');assert.match(html,/id="workspace" hidden/);assert.match(html,/security-auth.js/);assert.match(html,/Content-Security-Policy/);assert.ok(!/pyodide|eval\(/i.test(html));});

test("cloud receipt order cannot turn an older pass into the latest attempt",()=>{const t=tasks[0],old={...event(t,true),recorded_at:"2026-09-26T13:00:00Z"},recent={...event(t,false),client_at:"2026-09-24T12:00:00Z",recorded_at:"2026-09-26T12:00:00Z"};assert.equal(core.facts([old,recent],t).latest.payload.passed,false);});
