/* One guided course map over the existing activities. No task contracts or grades are rewritten. */
(async function(){
 'use strict';
 const $=id=>document.getElementById(id),core=T08PathCore;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let data,map,ledger,profile,events=[],foundation,progress,selected,stage='foundation',view='map',whole=false,zoom=1,gateTimer;
 let reflectionDirty=false;
 const label={done:'Done',todo:'Not yet',retry:'Needs work',stale:'Review again',unavailable:'Unavailable'};
 function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>$('toast').hidden=true,6000);}
 function status(s){$('saveStatus').textContent=s;$('syncDetail').textContent=s;}
 function href(id,s){return '#'+new URLSearchParams({view:'map',objective:id,...(s?{stage:s}:{})});}
 function navigate(id,s){if(reflectionDirty&&!confirm('Your reflection has unsaved edits. Leave this reflection?'))return;reflectionDirty=false;location.hash=href(id,s);}
 async function refresh(){events=await ledger.all();foundation=core.readFoundation(localStorage,profile.id,data.course);progress=core.evaluate(map,foundation,events);}
 function accountUI(){$('accountName').textContent='Signed in as '+(profile.username||'approved learner');$('toggleSync').textContent=ledger.enabled?'Disable cloud sync':'Enable cloud sync';$('syncNow').disabled=!ledger.enabled;}
 async function sync(){const active=ledger;if(!active?.enabled)return;try{await active.sync(FC.client,s=>{if(active===ledger)status(s);});if(active!==ledger)return;await refresh();if(!reflectionDirty)render();}catch(e){toast(e.message);}accountUI();}
 async function append(payload){await ledger.append(payload);await refresh();status('Saved locally'+(ledger.enabled?' · cloud sync queued':' · cloud sync off'));if(ledger.enabled)setTimeout(sync,1000);document.dispatchEvent(new CustomEvent('t08-evidence-updated'));}
 function route(){const p=new URLSearchParams(location.hash.slice(1));view=['map','progress','tools'].includes(p.get('view'))?p.get('view'):'map';selected=map.nodes.find(n=>n.id===p.get('objective'))||core.next(map,progress)||map.nodes.at(-1);stage=core.STAGES.includes(p.get('stage'))?p.get('stage'):progress.get(selected.id).nextStage.id;render();}
 function render(){if(!ledger)return;document.querySelectorAll('[data-main-view]').forEach(a=>a.setAttribute('aria-current',a.dataset.mainView===view?'page':'false'));T08Notebook.setContext(selected);if(view==='tools')return renderTools();if(view==='progress')return renderProgress();renderMap();}
 function completed(){return [...progress.values()].filter(x=>x.complete).length;}
 function graphSVG(){const layout=core.graphLayout(map,selected.id,whole),pos=layout.positions;const before=new Set(selected.requires),after=new Set(map.nodes.filter(n=>n.requires.includes(selected.id)).map(n=>n.id));let paths='';
  for(const n of layout.nodes)for(const id of n.requires){if(!whole&&n.id!==selected.id&&id!==selected.id)continue;const a=pos.get(id),b=pos.get(n.id);if(!a||!b)continue;let d;
   if(layout.direction==='horizontal'){const x=a.x+a.width,y=a.y+a.height/2,end=b.x,ey=b.y+b.height/2;d=`M${x},${y} C${x+30},${y} ${end-30},${ey} ${end},${ey}`;}
   else{const x=a.x+a.width/2,y=a.y+a.height,end=b.x+b.width/2,ey=b.y;d=`M${x},${y} C${x},${y+35} ${end},${ey-35} ${end},${ey}`;}
   paths+=`<path class="graph-edge ${n.id===selected.id||id===selected.id?'related':''}" d="${d}" marker-end="url(#pathArrow)"/>`;
  }
  function wrap(title){const words=title.split(' '),lines=[''];for(const w of words){if((lines.at(-1)+' '+w).trim().length>29&&lines.at(-1))lines.push(w);else lines[lines.length-1]=(lines.at(-1)+' '+w).trim();}return lines.slice(0,2).map((line,i)=>esc(line+(i===1&&lines.length>2?'…':'')));}
  const boxes=layout.nodes.map(n=>{const p=progress.get(n.id),b=pos.get(n.id),lines=wrap(n.title);return `<g role="button" tabindex="0" aria-label="Objective ${n.number}: ${esc(n.title)}. ${p.complete?'Complete':p.missing.length?p.missing.length+' recommended prerequisites unfinished':'Available'}." aria-pressed="${n.id===selected.id}" data-node="${n.id}" class="graph-node ${n.id===selected.id?'selected':''} ${p.complete?'done':''}" transform="translate(${b.x},${b.y})"><title>${esc(n.goal)}</title><rect width="${b.width}" height="${b.height}" rx="8"/><text x="17" y="24" class="gn-number">${String(n.number).padStart(2,'0')} / ${p.complete?'COMPLETE':n.id===selected.id?'SELECTED OBJECTIVE':before.has(n.id)?'PREREQUISITE':after.has(n.id)?'BUILDS TOWARD':'OBJECTIVE'}</text>${lines.map((t,i)=>`<text x="17" y="${49+i*19}" class="gn-title">${t}</text>`).join('')}<text x="17" y="98" class="gn-small">Foundation ${p.stages[0].completed}/${p.stages[0].items.length} · Practice ${p.stages[1].completed}/${p.stages[1].items.length}</text><text x="17" y="117" class="gn-small">Apply ${p.stages[2].completed}/${p.stages[2].items.length} · Review ${p.stages[3].completed}/${p.stages[3].items.length}</text></g>`;}).join('');
  return `<svg id="courseGraph" class="graph-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${layout.width} ${layout.height}" width="${layout.width}" height="${layout.height}" aria-label="${whole?'Entire course prerequisite graph':'Prerequisites and next objectives'}"><defs><marker id="pathArrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0 0 L10 5 L0 10z" fill="#bca28f"/></marker></defs>${!whole?'<text x="26" y="25" class="graph-label">KNOWLEDGE YOU BUILD ON</text><text x="366" y="25" class="graph-label">CURRENT OBJECTIVE</text><text x="706" y="25" class="graph-label">WHAT THIS ENABLES</text>':''}${paths}${boxes}</svg>`;
 }
 function outline(){return `<aside class="path-outline" aria-label="All course objectives"><div class="path-outline-head"><h2>Course outline</h2><label class="nb-sr" for="objectiveSearch">Find an objective</label><input id="objectiveSearch" type="search" placeholder="Find a topic or project"></div>${map.phases.map((phase,i)=>`<details class="path-phase" ${phase.id===selected.phase?'open':''}><summary>${i+1}. ${esc(phase.title)}</summary><ol>${map.nodes.filter(n=>n.phase===phase.id).map(n=>{const p=progress.get(n.id);return `<li data-search-title="${esc(n.title.toLowerCase())}"><button class="path-node ${n.id===selected.id?'selected':''} ${p.complete?'done':''}" data-node="${n.id}" ${n.id===selected.id?'aria-current="step"':''}><span class="num">${String(n.number).padStart(2,'0')}</span><span><strong>${esc(n.title)}</strong><small>${p.complete?'Complete':p.needsWork?'Latest attempt needs work':p.started?p.doneCount+'/'+p.total+' activities':p.missing.length?'Prerequisites listed · browse anytime':'Ready to begin'}</small></span></button></li>`;}).join('')}</ol></details>`).join('')}</aside>`;}
 function renderMap(){
  const p=progress.get(selected.id), next=core.next(map,progress);
  $('content').innerHTML=`<section class="linear-course-head">
    <div><span class="path-kicker">OBJECTIVE ${String(selected.number).padStart(2,'0')} OF ${map.nodes.length} / ${esc(map.phases.find(x=>x.id===selected.phase).title)}</span>
    <h1>${esc(selected.title)}</h1><p>${esc(selected.goal)}</p></div>
    <div class="linear-progress"><strong>${completed()} / ${map.nodes.length}</strong><small>objectives complete</small></div>
  </section>
  ${foundation.warning?`<div class="path-warning">${esc(foundation.warning)}</div>`:''}
  <details class="linear-philosophy"><summary>How Tomato08 trains this skill</summary><p><b>Acquire → Burn in & rotate → Integrate & operate → Retain & prove.</b> Mechanics become automatic through varied repetition; unfamiliar problems prove that you understand when and why to use the tool.</p></details>
  <section id="objectiveDetail" class="linear-objective" aria-label="Objective steps"></section>
  <section class="linear-finish">
    <span class="path-kicker">${p.complete?'OBJECTIVE COMPLETE':'END OF THIS OBJECTIVE'}</span>
    <h2>${p.complete?'Move to the next capability.':'Finish the steps above before moving on.'}</h2>
    <p>${p.complete?'The next topic builds on what you just made automatic.':'You can browse ahead, but unfinished work stays unfinished.'}</p>
    <div class="path-actions"><button class="primary" data-action="nextObjective">Next topic →</button><button data-action="notes">Notes</button></div>
  </section>
  <details class="linear-overview"><summary>Course overview / jump to another topic</summary>${outline()}</details>
  <p class="path-bottom">Completion is recorded work, not a proctored credential. Reading, self-review, and imported local checks remain distinct.</p>`;
  renderDetail();
 }
 function renderDetail(){
  const p=progress.get(selected.id), prereqs=selected.requires.map(id=>progress.get(id));
  const stageCopy={
   foundation:'Build the mental model first. Understand what the tool is and why it behaves that way.',
   practice:'Repeat until mechanics stop consuming attention. Change the angle: predict, vary, break, diagnose, repair, and compare.',
   apply:'Combine old and new tools in fresh problems. The prompt may not tell you which construct to use.',
   review:'Come back after time has passed. Explain failures and tradeoffs, then prove the skill survived without guidance.'
  };
  const sections=p.stages.map((s,si)=>`<section id="stage-${s.id}" class="linear-stage ${s.done?'done':''}">
    <header><span class="linear-step-number">${si+1}</span><div><span class="path-kicker">${esc(s.title)}</span><h2>${esc(s.title)}</h2><p>${esc(stageCopy[s.id])}</p></div><span class="linear-stage-count">${s.completed}/${s.items.length}</span></header>
    <ol class="linear-task-list">${s.items.map((item,i)=>`<li class="linear-task ${item.status}">
      <span class="task-index">${i+1}</span><div class="task-copy">
      ${item.rule.type==='reflection'?`<strong>${esc(item.title)}</strong>`:`<div class="linear-task-title">${esc(item.title)}</div>`}
      <small>${esc(item.where)}${item.delayed?' · delayed retention is tracked separately.':''}</small>
      ${item.rule.type!=='reflection'?`<a class="linear-open-task" href="${esc(item.href)}"><span>OPEN STEP ${i+1}</span><b>${esc(item.title)}</b><span aria-hidden="true">→</span></a>`:''}
      ${item.provenance&&item.done?`<small>${esc(item.provenance)}</small>`:''}
      ${item.ack?`<div class="path-actions"><button data-ack="${item.rule.step}">${item.done?'Preparation recorded':'Mark preparation complete'}</button></div>`:''}
      ${item.rule.type==='reflection'?`<div class="path-note"><label for="reviewText">What worked, what failed, and what will you do differently?</label><textarea id="reviewText" maxlength="5000" placeholder="At least 40 characters.">${esc(p.reflection?.payload.text||'')}</textarea><button data-action="saveReflection">Save reflection</button><p class="path-note-status">${p.readyReview?'Ready to finish review after saving.':'Finish the required work above, then save this review.'}</p></div>`:''}
      </div><span class="task-flag">${label[item.status]}</span></li>`).join('')}</ol>
    ${si<p.stages.length-1?`<div class="linear-down"><span>↓</span><small>Continue directly to ${esc(p.stages[si+1].title)}</small></div>`:''}
  </section>`).join('');
  $('objectiveDetail').innerHTML=`${p.missing.length?`<div class="path-warning"><b>Builds on unfinished work:</b> ${prereqs.filter(x=>!x.complete).map(x=>`<a href="${href(x.node.id)}">${esc(x.node.title)}</a>`).join(', ')}. You may inspect this objective, but the earlier evidence remains unfinished.</div>`:''}${sections}`;
 }
 function fitGraph(){const svg=$('courseGraph'),scroll=$('graphScroll');if(!svg||!scroll)return;const w=svg.viewBox.baseVal.width,h=svg.viewBox.baseVal.height,ratio=Math.max(.45,Math.min(1,(scroll.clientWidth-2)/w))*zoom;svg.setAttribute('width',Math.round(w*ratio));svg.setAttribute('height',Math.round(h*ratio));}
 function renderProgress(){$('content').innerHTML=`<section class="path-hero"><div><span class="path-kicker">YOUR LEARNING RECORD</span><h1>Progress, with its evidence.</h1><p>One overview. Foundation records stay local; projects, drills, notebook notes, and path reviews use the existing optional sync.</p></div></section><div class="path-stat-grid"><section class="path-card"><strong>${completed()}/${map.nodes.length}</strong><p>Completed objectives</p></section><section class="path-card"><strong>${[...progress.values()].filter(p=>p.needsWork).length}</strong><p>Objectives with a latest failed attempt</p></section><section class="path-card"><strong>${events.filter(e=>T08NotesCore.valid(e)).length}</strong><p>Saved notebook revisions, not skill credit</p></section></div><section class="path-card"><h2>Course record</h2><ol class="path-progress-list">${map.nodes.map(n=>{const p=progress.get(n.id);return `<li><div><strong>${String(n.number).padStart(2,'0')}. ${esc(n.title)}</strong><small>${p.stages.map(s=>s.title+': '+s.completed+'/'+s.items.length).join(' · ')}${p.needsWork?' · Latest attempt needs attention':''}</small></div><a class="path-button" href="${href(n.id,p.nextStage.id)}">${p.complete?'Review':'Continue'}</a></li>`;}).join('')}</ol></section><div class="path-actions"><a class="path-button" href="index.html#view=evidence">Foundation attempt details</a><a class="path-button" href="practice.html#view=history">Python attempt details</a><a class="path-button" href="projects.html#view=history">Project attempt details</a></div>`;}
 function renderTools(){$('content').innerHTML=`<section class="path-hero"><div><span class="path-kicker">TOOLS, NOT EXTRA COURSE PATHS</span><h1>Everything needed to keep moving.</h1><p>The map is the main entrance. These controls support the work rather than creating more parallel courses.</p></div></section><div class="path-grid"><section class="path-card"><h2>Computer setup</h2><p>Use a development environment for C, Python, and full projects. The website stores assignments and evidence; it does not run your programs.</p><div class="path-actions"><a class="path-button" href="index.html#view=setup">Foundation setup</a><a class="path-button" href="practice.html#view=setup">Python setup</a><a class="path-button" href="projects.html#view=setup">Project setup</a></div></section><section class="path-card"><h2>Notebook</h2><p>Keep explanations, code snippets, and questions next to your lesson. Link notes with [[Title]]; backlinks show related notes. The preview is text-based and never runs embedded HTML or Python.</p><button data-action="notes">Open notebook</button><p>Notes are learning aids. Writing one never completes a quiz or coding assignment.</p></section><section class="path-card"><h2>Mixed practice</h2><p>Return to selected Python topics, your recent failures, or material due for review without changing the guided path.</p><a class="path-button" href="practice.html#view=mixed">Build a practice session</a></section><section class="path-card"><h2>Backups and recovery</h2><p>Export before clearing browser data. The complete recovery file contains Foundation bytes and all shared-ledger events, including notebook revisions. It excludes authentication tokens. Notebook JSON also has its own import control.</p><button data-action="backup">Export complete recovery backup</button><label for="recoveryFile">Restore a map recovery backup</label><input id="recoveryFile" type="file" accept=".json,application/json"><p>Restoration merges immutable ledger events. It does not overwrite Foundation history; it downloads that part separately for review and the original Foundation import tools.</p></section></div>`;$('recoveryFile').onchange=e=>restoreRecovery(e.target.files[0]).catch(e=>toast(e.message));}
 function download(name,body){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([body],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
 async function backup(){await T08Notebook.flush();await refresh();const records={};for(const prefix of ['tomato08_cs50_safe_','tomato08_cs50_v1_']){const k=prefix+profile.id,raw=localStorage.getItem(k);if(raw!==null)records[k]=raw;}download('Tomato08-complete-learning-backup.json',JSON.stringify({kind:'tomato08-course-recovery',schema:1,account:profile.id,exported:new Date().toISOString(),foundation:records,ledger:{kind:'tomato08-project-backup',schema:2,events}},null,2));}
 async function restoreRecovery(file){if(!file)return;if(file.size>40000000)throw new Error('Recovery file exceeds 40 MB.');const raw=JSON.parse(await file.text());if(raw.kind!=='tomato08-course-recovery'||raw.schema!==1||!Array.isArray(raw.ledger?.events)||raw.ledger.events.length>20000||!raw.foundation||typeof raw.foundation!=='object')throw new Error('Unrecognized recovery file. Nothing changed.');const incoming=raw.ledger.events.map(e=>({...T08ProjectCore.validateEvent(e),synced:false}));T08ProjectCore.mergeEvents(events,incoming);if(!confirm('Merge the backup into this account? Current ledger history stays intact. Foundation bytes are downloaded separately, not overwritten.'))return;await T08Notebook.flush();await ledger.merge(incoming);await refresh();download('Tomato08-preserved-foundation-records.json',JSON.stringify(raw.foundation,null,2));toast('Ledger merged. Foundation data preserved separately for review.');if(ledger.enabled)sync();render();}
 $('content').addEventListener('input',e=>{if(e.target.id==='reviewText')reflectionDirty=true;if(e.target.id==='objectiveSearch'){const q=e.target.value.toLowerCase();document.querySelectorAll('[data-search-title]').forEach(li=>{li.hidden=!li.dataset.searchTitle.includes(q);if(q&&!li.hidden)li.closest('details').open=true;});}});
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-node],button');if(!b)return;try{
  if(b.dataset.node){navigate(b.dataset.node);return;}if(b.dataset.stage){navigate(selected.id,b.dataset.stage);return;}
  if(b.dataset.ack){await append({type:'trace',kind:'path-step',release_id:'path-'+selected.id,path_version:core.VERSION,step:b.dataset.ack});renderDetail();return;}
  const a=b.dataset.action;
  if(a==='whole'){whole=!whole;zoom=1;renderMap();}if(a==='zoomIn'||a==='zoomOut'){zoom=Math.min(1.7,Math.max(.5,zoom+(a==='zoomIn'?.15:-.15)));fitGraph();}if(a==='fit'){zoom=1;fitGraph();}
  if(a==='openDetails')$('objectiveDetail').scrollIntoView({block:'start'});
  if(a==='focusNext'){const n=core.next(map,progress)||selected;whole=false;navigate(n.id);}
  if(a==='nextObjective'){const p=progress.get(selected.id),n=map.nodes[map.nodes.indexOf(selected)+1];if(!n){toast('End of the course map. Review your evidence or revisit a project.');return;}if(!p.complete&&!confirm('This objective has unfinished work. Browse the next objective anyway? Progress will not be marked complete.'))return;navigate(n.id);}
  if(a==='saveReflection'){const text=$('reviewText').value.trim();if(text.length<40)throw new Error('Write at least 40 characters describing your takeaway.');await append({type:'reflection',kind:'objective-review',release_id:'path-'+selected.id,path_version:core.VERSION,evidence_ids:progress.get(selected.id).evidence,text});reflectionDirty=false;renderMap();toast('Reflection saved. Reading and reflection never replace coding evidence.');}
  if(a==='notes'||b.id==='notesButton')await T08Notebook.open(selected);
  if(a==='backup'||b.id==='backup')await backup();
  if(b.id==='accountButton'){accountUI();$('accountDialog').showModal();}
  if(b.id==='toggleSync'){if(!ledger.enabled&&!confirm('Enable private cloud sync for practice, projects, notebook notes and path reviews? This includes saved source and notes and is not end-to-end encrypted.'))return;ledger.enabled=!ledger.enabled;await ledger.setting('cloud',ledger.enabled);accountUI();if(ledger.enabled)await sync();else status('Local work retained · cloud sync off');}
  if(b.id==='syncNow')await sync();if(b.id==='signout'){await T08Notebook.flush();const res=await FC.client.auth.signOut();if(res.error)throw res.error;lock('Signed out. Sign in again to open your learning record.');}
 }catch(error){toast(error.message);}});
 document.addEventListener('keydown',e=>{const n=e.target.closest('[data-node]');if(n&&e.target.tagName.toLowerCase()==='g'&&['Enter',' '].includes(e.key)){e.preventDefault();navigate(n.dataset.node);}});
 function lock(text){T08Notebook.lock();clearInterval(gateTimer);ledger?.close();ledger=null;events=[];$('main').hidden=true;$('content').replaceChildren();$('gate').hidden=false;$('gateMessage').textContent=text;if($('accountDialog').open)$('accountDialog').close();}
 window.addEventListener('hashchange',()=>{if(ledger)route();});window.addEventListener('resize',fitGraph);
 window.addEventListener('beforeunload',e=>{if(reflectionDirty){e.preventDefault();e.returnValue='';}});
 window.addEventListener('pageshow',async e=>{if(e.persisted&&ledger){await refresh();render();}});
 window.addEventListener('storage',async e=>{if(ledger&&e.key?.includes(profile.id)&&!reflectionDirty){await refresh();render();}});
 document.addEventListener('t08-evidence-updated',async()=>{if(ledger){await refresh();}});
 try{
  if(!window.FC)throw new Error('Account service unavailable. Reload with a connection.');profile=await FC.requireUser();if(!profile)throw new Error('Sign in with your approved Tomato08 account.');
  data=await T08PathData.load();map=data.map;ledger=await new T08ProjectLedger(profile.id).open();await refresh();$('gate').hidden=true;$('main').hidden=false;route();accountUI();status('Existing evidence loaded · '+(ledger.enabled?'cloud sync enabled':'saved on this device'));
  ledger.channel&&(ledger.channel.onmessage=async e=>{if(e.data.account!==profile.id)return;await refresh();if(!reflectionDirty)render();});
  FC.client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||session&&session.user.id!==profile.id)lock('Your session changed. Sign in again.');});
  gateTimer=setInterval(async()=>{if(!ledger||document.hidden||!navigator.onLine)return;const res=await FC.client.rpc('security_access_status');if(!res.error&&res.data&&!res.data.allowed)lock('This session is no longer authorized.');},60000);
  if(ledger.enabled)await sync();
 }catch(error){$('gateMessage').textContent=error.message;}
 window.T08CoursePath={get data(){return data;},get ledger(){return ledger;},get progress(){return progress;},get selected(){return selected;},refresh,route};
})();
