/* Inline notebook on every learning page. No HTML execution or external service required. */
(function(){
 'use strict';
 const core=window.T08NotesCore,$=id=>document.getElementById(id);
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let ledger=null,profile=null,events=[],all=[],current=null,dirty=false,revision=0,parents=[],timer,chain=Promise.resolve(),syncTimer,gateTimer,locked=false,map=null;
 let context=null,opened=false,showArchive=false,lastFocus=null,opening=null;
 const ui=document.createElement('aside');ui.id='t08Notebook';ui.className='t08-notebook';ui.hidden=true;ui.setAttribute('aria-label','Course notebook');
 ui.innerHTML=`<div class="nb-head"><div><span class="path-kicker">YOUR WORKING NOTES</span><h2>Notebook</h2></div><button id="nbClose" aria-label="Close notebook">×</button></div><p id="nbContext" class="nb-context"></p><div class="nb-find"><label class="nb-sr" for="nbSearch">Search notes</label><input id="nbSearch" type="search" placeholder="Search titles and note text"><button id="nbNew">New</button></div><div class="nb-filter"><label><input id="nbThisTopic" type="checkbox"> This objective</label><label><input id="nbArchived" type="checkbox"> Archived</label></div><div id="nbList" class="nb-list" aria-label="Your notes"></div><div id="nbEditor" hidden><label for="nbTitle">Title</label><input id="nbTitle" maxlength="140"><div id="nbConflict" class="nb-warning" hidden></div><label for="nbText">Notes <span class="nb-muted">Markdown and [[note links]]</span></label><textarea id="nbText" maxlength="50000" spellcheck="false" placeholder="Explain it in your own words. Save snippets, questions, and connections.\n\nLink another note with [[Note title]]."></textarea><div class="nb-tools"><button id="nbSave">Save now</button><button id="nbPreviewButton" aria-pressed="false">Preview</button><button id="nbLinkTopic">Attach current topic</button><button id="nbArchive">Archive</button></div><p id="nbAttached" class="nb-muted"></p><div id="nbPreview" class="nb-preview" hidden></div><section class="nb-relations"><h3>Linked notes</h3><div id="nbLinks"></div><h3>Backlinks</h3><div id="nbBacklinks"></div></section><details><summary>Revision history</summary><div id="nbHistory"></div></details></div><p id="nbStatus" role="status" class="nb-status">Opening your account notebook…</p><details class="nb-backup"><summary>Backup, import & storage</summary><p>Saved on this device under your approved account. Optional Studio cloud sync includes these notes and is not end-to-end encrypted. Export before clearing site data. Archived notes and old revisions remain in backups.</p><div class="nb-tools"><button id="nbBackup">Export notebook JSON</button><button id="nbImport">Import notebook JSON</button><button id="nbMarkdown">Export current .md</button></div></details><input id="nbImportFile" type="file" accept=".json,application/json" hidden>`;
 document.body.append(ui);
 function status(s){$('nbStatus').textContent=s;}
 function download(name,text){const u=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
 function init(){return opening||(opening=initialize().finally(()=>opening=null));}
 async function initialize(){
  if(ledger&&!locked)return;
  if(!window.FC||!window.T08ProjectLedger)throw new Error('Sign in through Tomato08 to use account notes.');
  profile=await FC.requireUser();if(!profile)throw new Error('Sign in with your approved account before opening notes.');
  ledger=await new T08ProjectLedger(profile.id).open();locked=false;
  FC.client.auth.onAuthStateChange((event,session)=>{if(event==='SIGNED_OUT'||session&&session.user.id!==profile?.id){lock();}});
  ledger.channel&&(ledger.channel.onmessage=async e=>{if(e.data.account!==profile.id)return;await refresh();if(dirty){status('Another page saved notes. Your draft is retained; conflicts are not overwritten.');return;}if(current){const n=all.find(x=>x.id===current.id);if(n)loadEditor(n);}renderList();});
  await refresh();gateTimer=setInterval(recheckAccess,60000);if(ledger.enabled)sync().catch(()=>{});
 }
 function lock(){locked=true;clearTimeout(timer);clearTimeout(syncTimer);clearInterval(gateTimer);ledger?.close();ledger=null;events=[];all=[];current=null;dirty=false;ui.hidden=true;opened=false;document.body.classList.remove('notes-open');$('nbTitle').value='';$('nbText').value='';$('nbList').replaceChildren();$('nbPreview').replaceChildren();['nbHistory','nbLinks','nbBacklinks','nbAttached','nbContext','nbConflict'].forEach(id=>$(id).replaceChildren());$('nbEditor').hidden=true;profile=null;status('Session changed. Sign in again.');}
 async function recheckAccess(){const active=ledger;if(!active||document.hidden||!navigator.onLine)return;try{const res=await FC.client.rpc('security_access_status');if(ledger===active&&!res.error&&res.data?.allowed===false)lock();}catch(_){/* Offline work remains local; cloud RLS still applies. */}}
 async function refresh(){if(!ledger)return;events=await ledger.all();all=core.notes(events);}
 async function sync(){const active=ledger;if(!active)return;active.enabled=!!await active.setting('cloud');if(!active.enabled)return;try{await active.sync(FC.client,s=>{if(ledger===active)status(s);});if(ledger!==active)return;await refresh();renderList();if(current&&!dirty){const n=all.find(n=>n.id===current.id);if(n)loadEditor(n);}}catch(e){status('Saved locally; cloud sync pending: '+e.message);}}
 function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(()=>sync(),2000);}
 function contextLabel(){return context?String(context.number).padStart(2,'0')+' · '+context.title:'General notes';}
 function setContext(node){context=node||null;$('nbContext').textContent='Alongside: '+contextLabel();if(opened){renderList();renderRelations();}}
 function renderList(){const q=$('nbSearch').value.trim().toLowerCase();const rows=all.filter(n=>n.archived===showArchive&&(!$('nbThisTopic').checked||context&&n.topics.includes(context.id))&&(!q||(n.title+' '+n.text).toLowerCase().includes(q)));
  $('nbList').innerHTML=rows.length?rows.map(n=>`<button class="nb-item ${current?.id===n.id?'selected':''}" data-note="${n.id}"><strong>${esc(n.title)}</strong><small>${n.conflict?'Conflicting revisions · ':''}${n.topics.length?'Linked to '+n.topics.length+' objective(s)':'General note'}</small></button>`).join(''):'<p class="nb-muted">No matching notes. Create one for this objective.</p>';
 }
 function loadEditor(n){current={...n};parents=n.heads.map(h=>h.id);dirty=false;revision++;$('nbEditor').hidden=false;$('nbTitle').value=n.title;$('nbText').value=n.text;$('nbText').disabled=n.conflict;$('nbTitle').disabled=n.conflict;$('nbSave').disabled=n.conflict;$('nbArchive').textContent=n.archived?'Restore from archive':'Archive';$('nbConflict').hidden=!n.conflict;
  if(n.conflict)$('nbConflict').innerHTML='<strong>Multiple versions are preserved.</strong><p>Choose a starting version. Edit it to combine changes, then save a merged revision.</p>'+n.heads.map((e,i)=>`<details><summary>Version ${i+1} · ${esc(new Date(e.client_at).toLocaleString())}</summary><pre>${esc(e.payload.text)}</pre><button data-merge="${e.id}">Start merge from this version</button></details>`).join('');
  status(n.conflict?'Resolve both versions before continuing.':'Saved locally'+(ledger?.enabled?' · cloud sync enabled':' · cloud sync off'));renderRelations();renderHistory();renderPreview();renderList();
 }
 function update(){if(!current||locked||current.conflict)return;current.title=$('nbTitle').value;current.text=$('nbText').value;dirty=true;revision++;status('Unsaved changes…');clearTimeout(timer);timer=setTimeout(()=>flush().catch(e=>status('Not saved: '+e.message)),850);if(!$('nbPreview').hidden)renderPreview();}
 function flush(){clearTimeout(timer);chain=chain.catch(()=>{}).then(async()=>{
  if(!dirty||!current||!ledger||locked)return;const n={...current},base=[...parents],v=revision,active=ledger;
  if(!n.title.trim())throw new Error('Give this note a title before leaving. Your text is still here.');
  if(n.title.length>140||n.text.length>50000)throw new Error('Note exceeds the title/text limit. Export it before leaving.');
  const original=all.find(x=>x.id===n.id)||n;const p=core.payload({...n,title:original.title},{title:n.title,text:n.text},base);const added=await active.append(p);if(ledger!==active)return;
  await refresh();const saved=all.find(x=>x.id===n.id);if(current?.id===n.id){parents=[added.id];if(v===revision){dirty=false;current={...saved};if(saved.conflict)loadEditor(saved);else{renderList();renderRelations();renderHistory();}}}
  status(dirty?'Saving newer edits…':'Saved locally'+(active.enabled?' · cloud sync queued':' · cloud sync off'));scheduleSync();document.dispatchEvent(new CustomEvent('t08-evidence-updated'));
 });return chain;}
 async function choose(id){await flush();const n=all.find(n=>n.id===id);if(n)loadEditor(n);}
 async function newNote(title){await flush();const n={id:'notebook-'+crypto.randomUUID(),title:title||context?.title||'Untitled note',text:'',topics:context?[context.id]:[],aliases:[],archived:false};await ledger.append(core.payload(n,{},[]));await refresh();loadEditor(all.find(x=>x.id===n.id));scheduleSync();$('nbText').focus();}
 function renderRelations(){if(!current)return;const linked=core.links(current.text);$('nbLinks').innerHTML=linked.length?linked.map(l=>{const found=core.resolve(all,l.target);return found.length===1?`<button data-note="${found[0].id}">${esc(l.label)}${found[0].archived?' (archived)':''}</button>`:found.length>1?`<p>${esc(l.label)}: duplicate titles. Use a unique title or the note ID.</p>`:`<button data-create-title="${esc(l.target.slice(0,140))}">Create “${esc(l.label)}”</button>`;}).join(''):'<p class="nb-muted">Use [[Note title]] to connect notes.</p>';
  const backs=core.backlinks(all,current.id);$('nbBacklinks').innerHTML=backs.length?backs.map(n=>`<button data-note="${n.id}">${esc(n.title)}</button>`).join(''):'<p class="nb-muted">No other notes link here yet.</p>';
  $('nbAttached').textContent='Topics: '+(current.topics.map(id=>map?.nodes.find(n=>n.id===id)?.title||id).join(' · ')||'None');
 }
 function renderHistory(){if(!current)return;const history=events.filter(e=>core.valid(e)&&e.payload.release_id===current.id).sort((a,b)=>b.client_at.localeCompare(a.client_at));$('nbHistory').innerHTML=history.slice(0,25).map(e=>`<details><summary>${esc(new Date(e.client_at).toLocaleString())} · ${esc(e.payload.title)}</summary><pre>${esc(e.payload.text)}</pre><button data-restore="${e.id}">Restore as a new revision</button></details>`).join('')+(history.length>25?'<p>Latest 25 shown. All revisions remain in JSON export.</p>':'');}
 function inline(text,parent){
  const pattern=/\[\[([^\]\n]+)\]\]|`([^`]+)`|\*\*([^*]+)\*\*/g;let pos=0;
  for(const m of text.matchAll(pattern)){parent.append(document.createTextNode(text.slice(pos,m.index)));if(m[1]){const [target,...label]=m[1].split('|'),a=document.createElement('button');a.type='button';a.textContent=label.join('|')||target;const found=core.resolve(all,target.trim());if(found.length===1)a.dataset.note=found[0].id;else if(!found.length)a.dataset.createTitle=target.trim().slice(0,140);else{a.disabled=true;a.title='Ambiguous title';}parent.append(a);}else{const e=document.createElement(m[2]?'code':'strong');e.textContent=m[2]||m[3];parent.append(e);}pos=m.index+m[0].length;}
  parent.append(document.createTextNode(text.slice(pos)));
 }
 function renderPreview(){const host=$('nbPreview');host.replaceChildren();if(!current)return;let code=null;
  for(const line of current.text.split('\n')){if(/^\s*```/.test(line)){if(code){host.append(code);code=null;}else code=document.createElement('pre');continue;}if(code){code.textContent+=line+'\n';continue;}const heading=line.match(/^(#{1,4})\s+(.*)$/),el=document.createElement(heading?'h'+Math.min(heading[1].length+1,5):'p');inline(heading?heading[2]:line,el);host.append(el);}if(code)host.append(code);
 }
 async function open(node){lastFocus=document.activeElement;opened=true;ui.hidden=false;document.body.classList.add('notes-open');if(node)setContext(node);try{await init();map=(await T08PathData.load()).map;renderList();if(!current){const n=all.find(n=>!n.archived&&context&&n.topics.includes(context.id));if(n)loadEditor(n);else $('nbEditor').hidden=true;}if(!current)status('Create a note for this topic, or search your notebook.');$('nbSearch').focus();}catch(e){status(e.message);}}
 async function close(){await flush();ui.hidden=true;opened=false;document.body.classList.remove('notes-open');lastFocus?.focus?.();}
 ui.addEventListener('input',e=>{if(['nbTitle','nbText'].includes(e.target.id))update();if(e.target.id==='nbSearch')renderList();});
 ui.addEventListener('change',e=>{if(e.target.id==='nbArchived'){showArchive=e.target.checked;renderList();}if(e.target.id==='nbThisTopic')renderList();});
 ui.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{
  if(b.id==='nbClose')return await close();if(b.id==='nbNew'){await init();return await newNote();}
  if(b.dataset.note)return await choose(b.dataset.note);if(b.dataset.createTitle)return await newNote(b.dataset.createTitle);
  if(b.dataset.merge){const e=events.find(x=>x.id===b.dataset.merge);current={...current,...e.payload,id:e.payload.release_id,conflict:false};$('nbText').disabled=false;$('nbTitle').disabled=false;$('nbSave').disabled=false;$('nbText').value=current.text;$('nbTitle').value=current.title;dirty=true;revision++;$('nbConflict').innerHTML='<p>Both original versions are preserved. Edit this version, then Save now to merge.</p>';return;}
  if(b.id==='nbSave')return await flush();
  if(b.id==='nbPreviewButton'){$('nbPreview').hidden=!$('nbPreview').hidden;b.setAttribute('aria-pressed',String(!$('nbPreview').hidden));renderPreview();}
  if(b.id==='nbLinkTopic'&&current&&context){if(current.conflict)throw new Error('Resolve the note conflict first.');current.topics=[...new Set([...current.topics,context.id])];dirty=true;revision++;await flush();renderRelations();}
  if(b.id==='nbArchive'&&current){if(current.conflict)throw new Error('Resolve the note conflict first.');await flush();if(!current.archived&&!confirm('Archive this note? It remains recoverable, including its revisions.'))return;current.archived=!current.archived;dirty=true;revision++;await flush();renderList();loadEditor(all.find(n=>n.id===current.id));}
  if(b.dataset.restore){await flush();if(current.conflict)throw new Error('Resolve the note conflict first.');const old=events.find(e=>e.id===b.dataset.restore);if(!old||!confirm('Restore this version as a new revision? Current history will be preserved.'))return;current={...current,title:old.payload.title,text:old.payload.text};$('nbTitle').value=current.title;$('nbText').value=current.text;dirty=true;revision++;await flush();}
  if(b.id==='nbBackup'){await flush();await refresh();download('Tomato08-notebook.json',JSON.stringify(core.backup(events,profile.id),null,2));}
  if(b.id==='nbMarkdown'&&current){download(core.safeFilename($('nbTitle').value,current.id),core.markdown({...current,title:$('nbTitle').value,text:$('nbText').value}));}
  if(b.id==='nbImport'){$('nbImportFile').value='';$('nbImportFile').click();}
 }catch(error){status(error.message);}});
 $('nbImportFile').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>20000000)throw new Error('Notebook backup exceeds 20 MB.');const incoming=core.readBackup(JSON.parse(await file.text()));if(!confirm('Merge this notebook into the signed-in account? Conflicting versions stay separate; nothing is silently replaced.'))return;await flush();await ledger.merge(incoming);await refresh();renderList();if(current)loadEditor(all.find(n=>n.id===current.id));scheduleSync();status('Notebook merged. Original revisions preserved.');}catch(e){status('Import stopped: '+e.message);}});
 document.addEventListener('click',async e=>{if(!dirty)return;const a=e.target.closest('a[href]');if(!a||e.defaultPrevented||a.target==='_blank'||a.hasAttribute('download')||e.ctrlKey||e.metaKey||e.shiftKey)return;const url=new URL(a.href,location.href);if(url.origin!==location.origin||url.pathname===location.pathname)return;e.preventDefault();try{await flush();location.assign(url.href);}catch(error){status('Navigation stopped: '+error.message);}},true);
 window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden&&dirty)flush().catch(e=>status(e.message));});
 window.addEventListener('online',()=>{if(ledger)sync();});
 window.T08Notebook={open,close,flush,setContext,lock,recheckAccess,get dirty(){return dirty;},get current(){return current;},get ledger(){return ledger;},get notes(){return all;}};
})();
